-- CreateTable
CREATE TABLE "CATEGORY" (
    "CATEGORY_ID" SERIAL NOT NULL,
    "NAME" TEXT NOT NULL,

    CONSTRAINT "CATEGORY_pkey" PRIMARY KEY ("CATEGORY_ID")
);

-- CreateTable
CREATE TABLE "FUNDRAISER" (
    "FUNDRAISER_ID" SERIAL NOT NULL,
    "ORGANIZER" TEXT NOT NULL,
    "CAPTION" TEXT NOT NULL,
    "TARGET_FUNDING" DECIMAL(65,30) NOT NULL,
    "CURRENT_FUNDING" DECIMAL(65,30) NOT NULL,
    "CITY" TEXT NOT NULL,
    "ACTIVE" BOOLEAN NOT NULL,
    "CATEGORY_ID" INTEGER,

    CONSTRAINT "FUNDRAISER_pkey" PRIMARY KEY ("FUNDRAISER_ID")
);

-- AddForeignKey
ALTER TABLE "FUNDRAISER" ADD CONSTRAINT "FUNDRAISER_CATEGORY_ID_fkey" FOREIGN KEY ("CATEGORY_ID") REFERENCES "CATEGORY"("CATEGORY_ID") ON DELETE SET NULL ON UPDATE CASCADE;
